#preload = ~/.config/wallpapers/snow.png
#preload = ~/.config/wallpapers/rezero.jpg
#preload = ~/.config/wallpapers/forest.png
preload = ~/.config/wallpapers/cat.png
#preload = ~/.config/wallpapers/sunflowers.png
wallpaper = , ~/.config/wallpapers/cat.png
