#preload = ~/.config/wallpapers/snow.png
#preload = ~/.config/wallpapers/rezero.jpg
#preload = ~/.config/wallpapers/forest.png
#preload = ~/.config/wallpapers/cat.png
#preload = ~/.config/wallpapers/mistytrees.jpg 
#preload = ~/.config/wallpapers/sunflowers.png
#preload = ~/.config/wallpapers/snowvillage.png
#wallpaper = eDP-1, ~/.config/wallpapers/cat.png

wallpaper {
      monitor = eDP-1
      path = ~/.config/wallpapers/cat.png
      fit_mode = cover
  }

splash = false
