listener {
  timeout = 300
  on-timeout = brightnessctl -s set 1%
  on-resume = brightnessctl -r
}


listener {
  timeout = 350
  on-timeout = playerctl pause

}

listener {
  timeout = 400
  on-timeout = pidof hyprlock || hyprlock
}

listener {
	timeout = 500
	on-timeout = systemctl suspend
	
}
